---
title: "Comparing BISTRP and GTBK"
authors: "Georgia Lattig, Sophie Chivers, Emily Rose Stringer"
output:     html_document
date: "2023-03-11"
---

## Load Packages and Data

```{r load-packages , include = FALSE}
library(tidyverse)
library(readxl)
library(readr)
library(lubridate)
library(janitor)
library(rlang)
library(ggridges)
library(leaflet)
library(sf)
library(lubridate)
library(forcats)
library(RColorBrewer)
install.packages("ggstats")
install.packages("ggstatsplot")
library(ggstats)
library(GGally)
library(gganimate)
library(ggimage)
library(ggplot2)
library(gifski)
library(png)
library(transformr)
```


```{r load-data, message = FALSE}
buis_turtle_measures <- read_csv("/cloud/project/data/buis_turtle_measures.csv", 
    col_types = cols(CDate = col_date(format = "%m/%d/%Y")))

GTBK_turtle_measures <- read_csv("/cloud/project/data/GTBK_turtle_measures.csv")

GTBK <- read_csv("/cloud/project/data/GTBK_data.csv")
```

## Data Cleaning

```{r clean-GTBK-turtle-measures}
translate <- c(CDate = "fecha", PrimaryTag = "marca_nombre", sp = "especie_nombre_latino", location = "lugar", sex = "sexo_correcto", ccw = "a_c_c", cclnuct = "l_c_c")

GTBK_turtle_measures <- rename(GTBK_turtle_measures, all_of(translate))

GTBK_turtle_measures <- GTBK_turtle_measures %>% 
  mutate(`Remi?` =
           if_else(numero_recaptura > 1, "yes", "no"))

GTBK_turtle_measures <- GTBK_turtle_measures %>% 
  subset(select = -c(nombre_tortuga, geografía, numero_recaptura))

GTBK_turtle_measures <- GTBK_turtle_measures %>% 
  mutate(sex =
           case_when(
             sex == "Hembra" ~ "female",
             sex == "Macho" ~ "male",
             sex == "Indefinido" ~ "juvenile"
           ))

GTBK_turtle_measures <- GTBK_turtle_measures[, c(1,2,3,8,4,5,6,7)]
```

```{r clean-buis-turtle-measures}
buis_turtle_measures <- buis_turtle_measures %>% 
  subset(select = -c(activityno, ApplyDate, cclnucn, cclnott))

buis_turtle_measures <- buis_turtle_measures %>% 
  mutate(sp =
           case_when(
             sp == "GR" ~ "Chelonia mydas",
             sp == "HB" ~ "Eretmochelys imbricata"
           ))
```

```{r merge-turtle-measures}
turtle_measures <- full_join(GTBK_turtle_measures, buis_turtle_measures)

turtle_measures <- turtle_measures %>% 
  mutate(year = year(CDate))

turtle_measures <- turtle_measures %>% 
  mutate(organization = 
           if_else(location == "Buck Island", "BISTRP", "GTBK"))
```

## Exploratory Data Visualization

```{r comparisons-GR-females-2022}
turtle_measures %>% 
  filter(sp == "Chelonia mydas",
         sex == "female",
         year == "2022",
         location != "NA") %>% 
  ggplot(aes(x = sp, y = cclnuct)) +
  geom_violin(fill = "chartreuse4", alpha = 0.7) +
  facet_wrap(~ location) +
  theme_minimal() +
  labs(title = "Curved Carapace Length of Female Green Sea Turtles",
       subtitle = "Measured on Buck Island, USVI and in Kino Bay, Mexico",
       x = "Species", 
       y = "Curved Carapace Length (cm)",
       fill = "Species")

#The issue here is that some values from area_de_monitorio had quotation marks in them and until I figure out how R will read them, a bunch of other 
```

```{r statistical-analysis-box-violin}

## Finalize this visualization, edit color and text, etc.

# turtle_measures %>% 
#   filter(year == "2022",
#          sp == "Chelonia mydas",
#          sex == "female") %>% 
# ggbetweenstats(organization, cclnuct,
#                plot.type = "boxviolin",
#                title = "Curved Carapace Length Measurements of Female Green Sea Turtles",
#                subtitle = "Measured by BISTRP and GTBK During the 2022 Monitoring Season",
#                xlab = "Organization",
#                ylab = "Curved Carapace Length (cm)",
#                results.subtitle = FALSE,
#                package = "RColorBrewer",
#                palette = "Dark2") +
#   theme(
#     axis.ticks = element_blank(),
#     axis.line = element_line(colour = "grey50"),
#     panel.grid = element_line(color = "#b4aea9"),
#     panel.grid.minor = element_blank(),
#     panel.grid.major.x = element_blank(),
#     panel.grid.major.y = element_line(linetype = "dashed"),
#     panel.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"),
#     plot.background = element_rect(fill = "#fbf9f4", color = "#fbf9f4"))
# 
# # source: https://r-graph-gallery.com/web-violinplot-with-ggstatsplot.html
```

```{r turtle-demographics-by-organization, fig.width = 8, fig.height = 5}
turtle_measures %>% 
  mutate(species = case_when(
    sp == "Chelonia mydas" ~ "Chelonia mydas (GR)",
    sp == "Eretmochelys imbricata" ~ "Eretmochelys imbricata (HB)",
    sp == "Lepidochelys olivacea" ~ "Lepidochelys olivacea (OR)")) %>% 
  filter(organization == "BISTRP" |
         organization == "GTBK") %>% 
  filter(year == "2022") %>% 
  filter(sp != "NA") %>% 
  ggplot(aes(x = species, fill = species)) +
  geom_bar(alpha = 0.8) + 
  scale_fill_manual(values = c("chartreuse4", "hotpink4", "goldenrod1")) +
  scale_x_discrete(labels = c("GR", "HB", "OR")) +
  facet_wrap(~ organization) +
  theme_bw() + 
  labs(title = "Species Demographics of Sea Turtles Monitored by BISTRP and GTBK",
       subtitle = "During the 2022 Monitoring Season",
       x = "Species",
       y = "Number of Turtles",
       fill = "Species") +
  theme(plot.title = element_text(size = 15, family = "Helvetica"),
        plot.subtitle = element_text(size = 13, family = "Helvetica"),
        strip.text.x = element_text(size = 13, family = "Helvetica", face = "bold"),
        axis.title.x = element_text(size = 13, family = "Helvetica", vjust = 0.1),
        axis.title.y = element_text(size = 13, family = "Helvetica", vjust = 0.2),
        axis.text.x = element_text(size = 11, family = "Helvetica"),
        axis.text.y = element_text(size = 11, family = "Helvetica"),
        legend.text = element_text(size = 11, family = "Helvetica"),
        legend.title = element_text(size = 13, family = "Helvetica")) +
    guides(color = guide_legend(override.aes = list(size = 1)))

ggsave("final_visualizations/organization_turtle_demographics.jpg", device = "jpg", dpi = 500)

```

```{r GTBK-turtle-demographics-by-location}
turtle_measures %>% 
  mutate(species = case_when(
    sp == "Chelonia mydas" ~ "Chelonia mydas (GR)",
    sp == "Eretmochelys imbricata" ~ "Eretmochelys imbricata (HB)",
    sp == "Lepidochelys olivacea" ~ "Lepidochelys olivacea (OR)")) %>% 
  filter(organization == "BISTRP" |
         organization == "GTBK") %>% 
  filter(year == "2022") %>% 
  filter(sp != "NA") %>% 
  ggplot(aes(x = species, fill = sex)) +
  geom_bar(alpha = 0.8) + 
  scale_fill_manual(values = c("mediumorchid4", "goldenrod1", "aquamarine3")) +
  scale_x_discrete(labels = c("GR", "HB", "OR")) +
  facet_wrap(~ organization) +
  theme_bw() + 
  labs(title = "Sex Distribution of Sea Turtles Monitored by BISTRP and GTBK",
       subtitle = "During the 2022 Monitoring Season",
       x = "Species",
       y = "Number of Turtles",
       fill = "Sex") +
  theme(plot.title = element_text(size = 15, family = "Helvetica"),
        plot.subtitle = element_text(size = 13, family = "Helvetica"),
        strip.text.x = element_text(size = 13, family = "Helvetica", face = "bold"),
        axis.title.x = element_text(size = 13, family = "Helvetica", vjust = 0.1),
        axis.title.y = element_text(size = 13, family = "Helvetica", vjust = 0.2),
        axis.text.x = element_text(size = 11, family = "Helvetica"),
        axis.text.y = element_text(size = 11, family = "Helvetica"),
        legend.text = element_text(size = 11, family = "Helvetica"),
        legend.title = element_text(size = 13, family = "Helvetica")) +
    guides(color = guide_legend(override.aes = list(size = 1)))

```

```{r GTBK-measurements-parallel-coordinates-experiment}
turtle_measures %>% 
  filter(year == "2022" |
         year == "2016" |
         year == "2018" |
         year == "2020",
         organization == "GTBK") %>%
  ggparcoord(columns = 5:6, groupColumn = 3,
             showPoints = TRUE,
             alphaLines = 0.3
             )
  
#learn more about this type of plot. what is the y axis? then maybe use a parallel coordinates chart to map 4 measurements GTBK recorded on each turtle. decide what filters to apply to the data and which groups to compare (species? sex?)
```


```{r GTBK-static-turtle-growth, fig.width = 8, fig.height = 5}
GTBK$fecha = as.Date(GTBK$fecha)

GTBK <- GTBK %>% 
  mutate(year = year(fecha))

GTBK <- GTBK %>% 
  subset(select = c(fecha, year, lugar, geografía, marca_nombre, nombre_tortuga, especie_nombre_latino, sexo_correcto, l_c_c, a_c_c, p_c, l_t_c, numero_recaptura))

GTBK %>% 
  group_by(marca_nombre) %>% 
  filter(numero_recaptura >= 3) %>% 
  count()



GTBK %>%
  filter(marca_nombre == "GT 12261" |            #Juana
       marca_nombre == "GT 1569" |               #originally Julian, now Pepe (lol)
       marca_nombre == "GT 5297" )  %>%          #Elvia
  mutate(marca_nombre = case_when(
    marca_nombre == "GT 12261" ~ "JUANA",
    marca_nombre == "GT 1569" ~ "PEPE",
    marca_nombre == "GT 5297" ~ "ELVIA"
  )) %>%
  ggplot(aes(x = year, y = l_c_c, color = marca_nombre, size = l_c_c)) +
  geom_line(linewidth = 1, show.legend = FALSE) +
  geom_point(size = 4, alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = c("indianred3", "goldenrod", "palegreen4")) +
  facet_wrap(~ marca_nombre) +
  coord_fixed(ratio = 0.3) +
  labs(title = "Growth of 3 Individual Female Green Sea Turtles Over Time",
       subtitle = "in Laguna la Cruz, Kino Bay, Mexico",
       x = "Year",
       y = "Curved Carapace Length (cm)") +
  theme_bw() +
  theme(plot.title = element_text(size = 14, family = "Helvetica"),
        plot.subtitle = element_text(size = 12, family = "Helvetica"),
        strip.text.x = element_text(size = 11, family = "Helvetica", face = "bold"),
        axis.title.x = element_text(size = 11, family = "Helvetica", vjust = -1),
        axis.title.y = element_text(size = 11, family = "Helvetica", vjust = 1),
        axis.text.x = element_text(size = 9, family = "Helvetica"),
        axis.text.y = element_text(size = 10, family = "Helvetica"),
        legend.title = element_text(size = 11, family = "Helvetica"),
        legend.text = element_text(size = 10, family = "Helvetica"),
        panel.spacing = unit(1, "lines"))
  
ggsave("final_visualizations/individual_growth_over_time.jpg", device = "jpg", dpi = 500)

```

```{r time-enabled-turtle-growth, fig.width = 10, fig.height = 6}
GTBK$year = as.integer(GTBK$year)

#The issue with the animation below is that it leaves out a point in all three turtles' graphs until the end of the animation. Why?

# GTBK %>%
#   filter(marca_nombre %in% c(
#     "GT 12261",
#     "GT 1569",
#     "GT 5297")) %>%
#   mutate(marca_nombre = case_when(
#     marca_nombre == "GT 12261" ~ "JUANA",
#     marca_nombre == "GT 1569" ~ "PEPE",
#     marca_nombre == "GT 5297" ~ "ELVIA"
#   )) %>%
#   ggplot(aes(year, l_c_c, color = marca_nombre)) +
#   geom_point(aes(year, l_c_c, group = year), size = 4, alpha = 0.7, show.legend = FALSE) +
#   geom_line(size = 1, alpha = 0.9, show.legend = FALSE) +
#     scale_color_manual(values = c("indianred3", "goldenrod", "palegreen4")) +
#     facet_wrap(~ marca_nombre) +
#   coord_fixed(ratio = 0.3) +
#   theme_bw() +
#   labs(title = "Growth of 3 Individual Female Green Sea Turtles",
#        subtitle = "Caught by GTBK in Laguna la Cruz, Mexico",
#        x = "Year",
#        y = "Curved Carapace Length (cm)") +
#   transition_reveal(along = year, keep_last = TRUE) +
#   ease_aes('linear')

# animate(p, fps=8, renderer = gifski_renderer(loop = FALSE))

```

## Final Visualizations

```{r}

```




