---
title: "Project: Data Exploration and Visualization"
output: html_document
date: "2023-02-22"
---

```{r load-packages}
library(tidyverse)
library(readxl)
library(readr)
library(lubridate)
#install.packages("janitor")
library(janitor)
library(rlang)
library(ggridges)
library(leaflet)
library(sf)
# install.packages("regeoboundaries")
library(rgeoboundaries)
# install.packages("remotes")
remotes::install_gitlab("dickoa/rgeoboundaries")
```

```{r load-data, message = FALSE}
GTBK_2010_2018 <- read_excel("data/GTBK_2010_2018.xls")

GTBK_2018_2023 <- read_excel("/cloud/project/data/GTBK_2018_2023.xlsx", 
    col_types = c("text", "text", "text", 
        "date", "numeric", "numeric", "numeric", 
        "text", "text", "numeric", "text", 
        "numeric", "numeric", "text", "date", 
        "numeric", "text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text", "numeric", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "numeric", "numeric", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "numeric"))

buis_2022 <- read_csv("/cloud/project/data/buis_turtle_measures.csv", 
    col_types = cols(CDate = col_date(format = "%m/%d/%Y")))

```

## Cleaning Data
```{r clean-species-variable-GTBK_2018_2023}
# GTBK_2018_2023 <- GTBK_2018_2023 %>%
#   mutate(especie_nombre_latino =
#            case_when(
#              especie == "Verde/Prieta" ~ "Chelonia mydas",
#              especie == "Carey" ~ "Eretmochelys imbricata",
#              especie == "Amarilla" ~ "Caretta caretta",
#              especie == "Golfina" ~ "Lepidochelys olivacea"
#              )
#          )
```

```{r clean-GTBK-column-names}
colnames(GTBK_2010_2018) <- c(
  "ID", 
  "Nombre tortuga",
  "No. Monitoreo",
  "Estacion", 
  "Fecha_original",
  "Fecha", 
  "Area de Monitoreo",
  "Posicion lat-long", 
  "Hora de captura",
  "Especie", 
  "Peso", 
  "Sexo", 
  "L.R.C.",
  "L.C.C.",
  "A.R.C.",
  "A.C.C.",
  "P.C",
  "L.P", 
  "L T C",
  "Recaptura", 
  "Marca Derecha",
  "Marca Izquierda", 
  "Observaciones y comentarios") 

GTBK_2010_2018 <- clean_names(GTBK_2010_2018)

colnames(GTBK_2018_2023) <- c(
  "id",
  "Responsable",
  "no monitoreo",
  "fecha_inicio",
  "hora_inicio",
  "hora_fin",
  "total_horas",
  "tipo monitoreo",
  "metodologia",
  "Longidud red o lanceos",
  "area_de_monitoreo",
  "latitud",
  "longitud",
  "unidad utm o grados",
  "fecha",
  "hora captura",
  "nombre_tortuga",
  "Especie",
  "L R C",
  "A R C",
  "L C C",
  "A C C",
  "P C",
  "L P",
  "L T C",
  "peso",
  "sexo",
  "Material_marcas",
  "Marca_derecha",
  "Marca izquierda" ,
  "Marca previa derecha",
  "Marca previa Izquierda",
  "PIT tag",
  "PIT nuevo",
  "PIT previo",
  "Muestra sangre",
  "Muestra piel",
  "Muestra cont estom",
  "Otra muestra",
  "Especificar",
  "Lesiones Balanos",
  "Foto",
  "observaciones y comentarios",
  "ID",
  "PIT previo",
  "Muestra sangre",
  "Muestra piel",
  "Muestra cont estom",
  "Otra muestra",
  "Especificar",
  "Lesiones Balanos",
  "Foto",
  "Comentarios",
  "ID"
  )

GTBK_2018_2023 <- clean_names(GTBK_2018_2023)
```

```{r coerce-variable-types}
#GTBK 2018-2023
GTBK_2018_2023$no_monitoreo <- as.double(GTBK_2018_2023$no_monitoreo)

#GTBK 2010-2018
GTBK_2010_2018$no_monitoreo <- as.double(GTBK_2010_2018$no_monitoreo)
GTBK_2010_2018$l_r_c <- as.double(GTBK_2010_2018$no_monitoreo)
GTBK_2010_2018$l_r_c <- as.double(GTBK_2010_2018$no_monitoreo)
GTBK_2010_2018$l_p <- as.double(GTBK_2010_2018$no_monitoreo)

```

```{r join-datasets}
GTBK_data <- full_join(GTBK_2018_2023, GTBK_2010_2018)
```

Below I am trying to create a clean, concise, merged dataset that only includes the columns we are interested in.

```{r create-clean-master-dataset}
GTBK <- GTBK_data %>% 
  select()
```

```{r clean-species-variable}
GTBK_data <- GTBK_data %>%
  mutate(especie_nombre_latino = 
           case_when(
             especie == "Verde/Prieta" ~ "Chelonia mydas",
             especie == "Chelonia mydas" ~ "Chelonia mydas",
             especie == "Carey" ~ "Eretmochelys imbricata", 
             especie == "Eretmochelys imbricata" ~ "Eretmochelys imbricata",
             especie == "Amarilla" ~ "Caretta caretta", 
             especie == "Golfina" ~ "Lepidochelys olivacea", 
             especie == "Lepidochelys olivacea" ~ "Lepidochelys olivacea"
             )
         )
```

```{r clean-sex-variab;e}
GTBK_data <- GTBK_data %>%
  mutate(sexo_correcto = 
           case_when(
             sexo == "indefinido" ~ "Indefinido",
             sexo == "Indefinido" ~ "Indefinido",
             sexo == "hembra" ~ "Hembra", 
             sexo == "Hembra" ~ "Hembra",
             sexo == "macho" ~ "Macho", 
             sexo == "Macho" ~ "Macho"
             ))
#Created variable `sexo-correcto` to combine lowercase and uppercase words, originally "Hembra" and "hembra" read as different values 
```


```{r count-especie-nombre-latino}
GTBK_data %>%
  group_by(especie_nombre_latino) %>%
count()  
```

```{r buis-22-species-measurements}
buis_2022 %>% 
  mutate(species = case_when(
    sp == "HB" ~ "Eretmochelys imbricata",
    sp == "GR" ~ "Chelonia mydas")
  ) %>% 
  ggplot(aes(x = species, y = cclnuct, fill = species)) +
  geom_violin() +
  scale_fill_manual(values = c("chartreuse4", "hotpink4")) + 
  theme_minimal() +
  coord_flip () +
  labs(title = "Average Curved Carapace Length of Green and Hawksbill Sea Turtles",
       subtitle = "Reproductive Females Measured During 2022 Nesting Season on Buck Island, USVI",
       x = "Species", 
       y = "Curved Carapace Length (cm)",
       fill = "Species")

buis_2022 %>% 
  mutate(species = case_when(
    sp == "HB" ~ "Eretmochelys imbricata",
    sp == "GR" ~ "Chelonia mydas")
  ) %>% 
  ggplot(aes(x = species, y = cclnuct, fill = species)) +
  geom_boxplot() +
  scale_fill_manual(values = c("chartreuse4", "hotpink4")) + 
  theme_minimal() +
  coord_flip () +
  labs(title = "Average Curved Carapace Length of Green and Hawksbill Sea Turtles",
       subtitle = "Reproductive Females Measured During 2022 Nesting Season on Buck Island, USVI",
       x = "Species", 
       y = "Curved Carapace Length (cm)",
       fill = "Species")
```


```{r GTBK-species-measurements}
# GTBK_data %>%
#   filter(especie_nombre_latino == "Chelonia mydas" |
#          especie_nombre_latino == "Eretmochelys imbricata" |
#          especie_nombre_latino == "Lepidochelys olivacea" |
#          especie_nombre_latino == "Caretta caretta") %>%
#   ggplot(aes(x = especie_nombre_latino, y = `4.ACC`, fill = especie_nombre_latino)) +
#   geom_boxplot() +
#   scale_fill_manual(values = c("goldenrod1","chartreuse4", "hotpink4","cornflowerblue")) +
#   theme_minimal() +
#   coord_flip() +
#   labs(title = "Curved Carapace Length Measurements of Four Sea Turtle Species",
#        subtitle = "Monitored by GTBK in Kino Bay, Mexico between 2010-2023",
#        x = "Species",
#        y = "Curved Carapace Length (cm)",
#        fill = "Species")

# GTBK_2010_2018 %>% 
#   filter(Especie == "Chelonia mydas" |
#          Especie == "Eretmochelys imbricata" |
#          Especie == "Lepidochelys olivacea" |
#          Especie == "Caretta Caretta") %>% 
#   ggplot(aes(x = Especie, y = `A.R.C.(cm)`, fill = Especie)) +
#   geom_boxplot() +
#   scale_fill_manual(values = c("chartreuse4", "hotpink4", "goldenrod1")) + 
#   theme_minimal() +
#   coord_flip() +
#   labs(title = "Curved Carapace Length Measurements of Three Sea Turtle Species",
#        subtitle = "Monitored by GTBK in Kino Bay, Mexico between 2010-2018",
#        x = "Species", 
#        y = "Curved Carapace Length (cm)",
#        fill = "Species")

# GTBK_2018_2023 %>% 
#   filter(especie_nombre_latino == "Chelonia mydas" |
#          especie_nombre_latino == "Eretmochelys imbricata" |
#          especie_nombre_latino == "Lepidochelys olivacea" |
#          especie_nombre_latino == "Caretta caretta") %>%
#   ggplot(aes(x = especie_nombre_latino, y = `4.ACC`, fill = especie_nombre_latino)) +
#   geom_boxplot() +
#   scale_fill_manual(values = c("goldenrod1","chartreuse4", "hotpink4","cornflowerblue")) + 
#   theme_minimal() +
#   coord_flip() +
#   labs(title = "Curved Carapace Length Measurements of Four Sea Turtle Species",
#        subtitle = "Monitored by GTBK in Kino Bay, Mexico between 2018-2023",
#        x = "Species", 
#        y = "Curved Carapace Length (cm)",
#        fill = "Species")
```

```{r clean-indentification-marking}
GTBK_data <- GTBK_data %>%
  unite(marca_nombre, marca_derecha, marca_previa_derecha, na.rm = TRUE)

number_recapture <- GTBK_data %>%
  group_by(marca_nombre) %>%
  count(marca_nombre) %>%
  arrange(desc(n)) 
```

```{r recapture-viz-1}
number_recapture %>% 
  filter(n %in% c(2, 3, 4)) %>% 
  ggplot(aes(x = n)) +
  geom_bar()
```

```{r seasonality}
# recapture_tibble <- GTBK_data %>%
#   group_by(marca_nombre) %>%
#   select(nombre_tortuga, fecha, especie, area_de_monitoreo, marca_nombre)
# 
# 
# recapture_tibble %>%
#   group_by(marca_nombre) %>%
#   summarize(marca_nombre)
```

```{r species-by-sex-counts}
GTBK_data %>%
  group_by(especie_nombre_latino) %>%
  count (sexo_correcto)

# GTBK_2018_2023 %>% 
#   group_by(especie_nombre_latino) %>% 
#   count(Sexo)

# GTBK_2010_2018 %>% 
#   group_by(Especie) %>% 
#   count(Sexo) 

buis_2022 %>% 
  group_by(sp) %>% 
  count(sex)

```

```{r species-sex-distribution}
GTBK_data %>%
  group_by(especie_nombre_latino) %>%
  count (sexo_correcto)
# how can we make this graph so it just includes individuals no recaptures?
# how to accurately remove NAs that correlate to 'no data collected' rather than not entered for an observation

ggplot(data = GTBK_data,
       mapping = aes(x = sexo_correcto, 
                     fill = sexo_correcto)) +
  geom_bar() + 
  facet_wrap( ~ especie_nombre_latino, scales = "free_y") +
   labs(title = "Species and Sex Distribution", 
       subtitle = "of turtles captured in Kino Bay", 
       x = "sex", 
       y = "number of individuals") +
 scale_fill_manual(values = c("#cd4071","#feca8d", "#721f81", "#000004"))

# how to show a different graph for each species, lots of Chelonia is throwing off the data
```

```{r missing-data}
library(visdat)
library(naniar)

visdat::vis_dat(GTBK_data)
visdat::vis_dat(GTBK_2010_2018)
visdat::vis_dat(GTBK_2018_2023)

visdat::vis_dat(buis_2022)
```
```{r}
naniar::gg_miss_var(GTBK_data)

visdat::vis_miss(GTBK_data)
visdat::vis_miss(GTBK_2018_2023)
```

```{r map-kino-bay-recapturs}
leaflet(GTBK_data) %>%
  addProviderTiles(providers$Esri.WorldImagery) %>% 
  setView(lng = -111.936302, 
          lat = 28.822747,
          zoom = 1) %>% 
  addCircleMarkers(~longitud, ~latitud,
                  fillColor = "red",
                  stroke = FALSE)
```

