---
title: "Comparing BISTRP and GTBK"
authors: "Georgia Lattig, Sophie Chivers, Emily Rose Stringer"
output:     html_document
date: "2023-03-11"
---

## Load Packages and Data

```{r load-packages , include = FALSE}
library(tidyverse)
library(readxl)
library(readr)
library(lubridate)
library(janitor)
library(rlang)
library(ggridges)
library(leaflet)
library(sf)
library(lubridate)
library(forcats)
library(RColorBrewer)
install.packages("ggstats")
install.packages("ggstatsplot")
library(ggstats)
library(GGally)
library(gganimate)
library(ggimage)
library(ggplot2)
library(gifski)
library(png)
library(transformr)
library(ggalluvial)
```


```{r load-data, message = FALSE}
buis_turtle_measures <- read_csv("/cloud/project/data/buis_turtles.csv", 
    col_types = cols(CDate = col_date(format = "%m/%d/%Y")))

GTBK_turtle_measures <- read_csv("/cloud/project/data/GTBK_turtle_measures.csv")

GTBK <- read_csv("/cloud/project/data/GTBK_data.csv")
```

## Data Cleaning

```{r clean-GTBK-turtle-measures}
translate <- c(CDate = "fecha", PrimaryTag = "marca_nombre", sp = "especie_nombre_latino", location = "lugar", sex = "sexo_correcto", ccw = "a_c_c", cclnuct = "l_c_c")

GTBK_turtle_measures <- rename(GTBK_turtle_measures, all_of(translate))

GTBK_turtle_measures <- GTBK_turtle_measures %>% 
  mutate(`Remi?` =
           if_else(numero_recaptura > 1, "yes", "no"))

GTBK_turtle_measures <- GTBK_turtle_measures %>% 
  subset(select = -c(nombre_tortuga, geografía, numero_recaptura))

GTBK_turtle_measures <- GTBK_turtle_measures %>% 
  mutate(sex =
           case_when(
             sex == "Hembra" ~ "female",
             sex == "Macho" ~ "male",
             sex == "Indefinido" ~ "juvenile"
           ))

GTBK_turtle_measures <- GTBK_turtle_measures[, c(1,2,3,8,4,5,6,7)]
```

```{r clean-buis-turtle-measures}
buis_turtle_measures <- buis_turtle_measures %>% 
  subset(select = -c(activityno, ApplyDate, cclnucn, cclnott))

buis_turtle_measures <- buis_turtle_measures %>% 
  mutate(sp =
           case_when(
             sp == "GR" ~ "Chelonia mydas",
             sp == "HB" ~ "Eretmochelys imbricata",
             sp == "LH" ~ "Caretta caretta"
           ))
```

```{r merge-turtle-measures}
turtle_measures <- full_join(GTBK_turtle_measures, buis_turtle_measures)

turtle_measures <- turtle_measures %>% 
  mutate(year = year(CDate))

turtle_measures <- turtle_measures %>% 
  mutate(organization = 
           if_else(location == "Buck Island", "BISTRP", "GTBK"))
```

## Exploratory Data Visualization

```{r comparisons-GR-females-2022}
turtle_measures %>% 
  filter(sp == "Chelonia mydas",
         sex == "female",
         year == "2022",
         location != "NA") %>% 
  ggplot(aes(x = sp, y = cclnuct)) +
  geom_violin(fill = "chartreuse4", alpha = 0.7) + 
  facet_wrap(~ location) +
  theme_minimal() +
  labs(title = "Curved Carapace Length of Female Green Sea Turtles",
       subtitle = "Measured on Buck Island, USVI and in Kino Bay, Mexico",
       x = "Species", 
       y = "Curved Carapace Length (cm)",
       fill = "Species")

#The issue here is that some values from area_de_monitorio had quotation marks in them and until I figure out how R will read them, a bunch of other 
```

```{r statistical-analysis-box-violin, fig.width = 11, fig.height = 6, fig.alt = "This chart displays each organization's distribution of female Green sea turtle Curved Carapace Length (CCL) measurements taken during the 2022 Season. The chart plots each measurement as a point and overlays both a boxplot and a violin plot to provide a lot of information about the data distributions. Female Green sea turtles measured by BISTRP were much larger,  with an average CCL of 110.69 cm while GTBK's female Greens had an average CCL of 81.90 cm. This plot also tells the sample size of each distribution. BISTRP measured 23 female Greens while GTBK measured 17."}

## Finalize this visualization, edit color and text, etc.

turtle_measures %>%
  filter(year == "2022",
         sp == "Chelonia mydas",
         sex == "female") %>%
ggbetweenstats(organization, cclnuct,
               plot.type = "boxviolin",
               title = "Curved Carapace Length Measurements of Female Green Sea Turtles",
               subtitle = "Measured by BISTRP and GTBK During the 2022 Season",
               xlab = "Organization",
               ylab = "Curved Carapace Length (cm)",
               results.subtitle = FALSE,
               package = "RColorBrewer",
               palette = "Dark2",
               centrality.point.args = list(size = 5, color = "darkred"),
               centrality.label.args = list(size = 3.5, family ="Helvetica",
                                            nudge_x = 0.4, segment.linetype = 4, min.segment.length = 0)) +
  theme(
    axis.ticks = element_blank(),
    axis.line = element_line(colour = "grey50"),
    panel.grid = element_line(color = "#b4aea9"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed"),
    panel.background = element_rect(fill = "white", color = "white"),
    plot.background = element_rect(fill = "white", color = "white"),
    text = element_text(family = "Helvetica", size = 12, color = "black"),
    plot.title = element_text(
      family = "Helvetica", 
      size = 13,
      face = "bold",
      color = "black"),
    axis.text.x = element_text(family = "Helvetica", size = 11, color = "black"),
    axis.title.x = element_text(family = "Helvetica", size = 12, face = "bold"),
    axis.title.y = element_text(family = "Helvetica", size = 12, face = "bold")
    )

ggsave("final_visualizations/ccl_geographical_comparison.jpg", device = "jpg", dpi = 500)

# # source: https://r-graph-gallery.com/web-violinplot-with-ggstatsplot.html
```

```{r turtle-demographics-by-organization, fig.width = 8, fig.height = 5}
turtle_measures %>% 
  group_by(PrimaryTag) %>% 
  mutate(species = case_when(
    sp == "Chelonia mydas" ~ "Chelonia mydas (GR)",
    sp == "Eretmochelys imbricata" ~ "Eretmochelys imbricata (HB)",
    sp == "Lepidochelys olivacea" ~ "Lepidochelys olivacea (OR)")) %>% 
  filter(organization == "BISTRP" |
         organization == "GTBK") %>% 
  filter(year == "2022") %>% 
  filter(sp != "NA") %>% 
  ggplot(aes(x = species, fill = species)) +
  geom_bar(alpha = 0.8) + 
  scale_fill_manual(values = c("chartreuse4", "hotpink4", "goldenrod1")) +
  scale_x_discrete(labels = c("GR", "HB", "OR")) +
  facet_wrap(~ organization) +
  theme_bw() + 
  labs(title = "Species Demographics of Sea Turtles Monitored by BISTRP and GTBK",
       subtitle = "During the 2022 Monitoring Season",
       x = "Species",
       y = "Number of Turtles",
       fill = "Species") +
  theme(plot.title = element_text(size = 15, family = "Helvetica"),
        plot.subtitle = element_text(size = 13, family = "Helvetica"),
        strip.text.x = element_text(size = 13, family = "Helvetica", face = "bold"),
        axis.title.x = element_text(size = 13, family = "Helvetica", vjust = 0.1),
        axis.title.y = element_text(size = 13, family = "Helvetica", vjust = 0.2),
        axis.text.x = element_text(size = 11, family = "Helvetica"),
        axis.text.y = element_text(size = 11, family = "Helvetica"),
        legend.text = element_text(size = 11, family = "Helvetica"),
        legend.title = element_text(size = 13, family = "Helvetica")) +
    guides(color = guide_legend(override.aes = list(size = 1)))

ggsave("final_visualizations/organization_turtle_demographics.jpg", device = "jpg", dpi = 500)

#Check to see if this graph includes duplicates of turtles that were recaptured within the 2022 nesting season.

turtle_measures %>% 
  filter(year == "2022") %>% 
  filter(organization == "GTBK") %>% 
  group_by(sp) %>% 
  count(sp)

#There were 79 Green turtles and 1 Olive Ridley turtle captured by GTBK during the 2022 season.

turtle_measures %>% 
  filter(year == "2022") %>% 
  filter(organization == "GTBK") %>% 
  filter(sp == "Chelonia mydas") %>% 
  count(PrimaryTag)

#There were 77 unique Green turtles captured by GTBK during the 2022 season. Two turtles were captured twice.
```

```{r GTBK-turtle-demographics-by-location, fig.width = 12, fig.height = 8 , fig.alt= "This bar chart shows the species and sex distribution of sea turtles monitored by BISTRP and GTBK during the 2022 season. The bar chart is faceted by organization and the data clearly reflects the different nature of each project. Because BISTRP monitors nesting turtles on a nesting beach, all sea turtles monitored by BISTRP in 2022 were adult females, pretty evenly split between 29 Hawksbill and 27 Green with one exceptional Loggerhead. GTBK on the other hand monitors sea turtles in Kino Bay through opportunistic in-water surveys. GTBK encountered mostly Green sea turtles, 79 of them, both males and females, as well as one Olive Ridley. The majority of Green turtles captured by GTBK, 59 out of 79, could not be sexed however because they were juvenile."}
turtle_measures %>% 
  mutate(species = case_when(
    sp == "Chelonia mydas" ~ "Green",
    sp == "Eretmochelys imbricata" ~ "Hawksbill",
    sp == "Lepidochelys olivacea" ~ "Olive Ridley",
    sp == "Caretta caretta" ~ "Loggerhead")) %>% 
  mutate(sex = factor(sex, levels = c("female","male","juvenile"))) %>% 
  filter(organization == "BISTRP" |
         organization == "GTBK") %>% 
  mutate(organization = case_when(
    organization == "GTBK" ~ "Grupo Tortuguero de Bahía Kino",
    organization == "BISTRP" ~ "Buck Island Sea Turtle Research Program")) %>% 
  filter(year == "2022") %>% 
  filter(sp != "NA") %>% 
  ggplot(aes(x = species, fill = sex)) +
  geom_bar(alpha = 0.8) + 
  # geom_text(aes(group = sex, label = after_stat(count)), stat = "count", position = position_stack(vjust = 0.5), size = 5) +
  scale_fill_manual(values = c("darkorchid4", "aquamarine3", "goldenrod1")) +
  # scale_x_discrete(labels = c("Green", "Hawksbill", "Olive Ridley")) +
  scale_y_continuous(breaks = seq(0, 80, by = 10)) +
  facet_wrap(~ organization, scales = "free_x") +
  theme_bw() + 
  labs(title = "Demographics of Sea Turtles Monitored by Two Research Programs During the 2022 Season",
       x = "Species",
       y = "Number of Turtles",
       fill = "Sex") +
  theme(plot.title = element_text(size = 15, family = "Helvetica"),
        plot.subtitle = element_text(size = 13, family = "Helvetica"),
        strip.text.x = element_text(size = 13, family = "Helvetica", face = "bold"),
        axis.title.x = element_text(size = 13, family = "Helvetica", vjust = 0.1),
        axis.title.y = element_text(size = 13, family = "Helvetica", vjust = 1),
        axis.text.x = element_text(size = 11, family = "Helvetica"),
        axis.text.y = element_text(size = 11, family = "Helvetica"),
        legend.text = element_text(size = 11, family = "Helvetica"),
        legend.title = element_text(size = 13, family = "Helvetica")) +
    guides(color = guide_legend(override.aes = list(size = 1)))

ggsave("final_visualizations/organization_turtle_demographics_sex.jpg", width = 10, height = 6, device = "jpg", dpi = 500)

```

```{r GTBK-measurements-parallel-coordinates-experiment}
turtle_measures %>% 
  filter(year == "2022" |
         year == "2016" |
         year == "2018" |
         year == "2020",
         organization == "GTBK") %>%
  ggparcoord(columns = 5:6, groupColumn = 3,
             showPoints = TRUE,
             alphaLines = 0.3
             )
  
#learn more about this type of plot. what is the y axis? then maybe use a parallel coordinates chart to map 4 measurements GTBK recorded on each turtle. decide what filters to apply to the data and which groups to compare (species? sex?)
```


```{r GTBK-static-turtle-growth, fig.width = 8, fig.height = 5, fig.alt= "This time-enabled animation tracks the growth of three female Green sea turtles--Elvia, Juana and Pepe--recaptured by GTBK over several years. The chart uses Curved Carapace Length (CCL) in centimeters as a standard measurement for growth. Each turtle has grown in size between recaptures but this is most evident in Pepe's case. Pepe had a CCL of about 52 cm when first captured in 2014 and grew almost 20 cm before being recaptured in 2017."}
GTBK$fecha = as.Date(GTBK$fecha)

GTBK <- GTBK %>% 
  mutate(year = year(fecha))

GTBK <- GTBK %>% 
  subset(select = c(fecha, year, lugar, geografía, marca_nombre, nombre_tortuga, especie_nombre_latino, sexo_correcto, l_c_c, a_c_c, p_c, l_t_c, numero_recaptura))

GTBK %>% 
  group_by(marca_nombre) %>% 
  filter(numero_recaptura >= 3) %>% 
  count()



GTBK %>%
  filter(marca_nombre == "GT 12261" |            #Juana
       marca_nombre == "GT 1569" |               #originally Julian, now Pepe (lol)
       marca_nombre == "GT 5297" )  %>%          #Elvia
  mutate(marca_nombre = case_when(
    marca_nombre == "GT 12261" ~ "JUANA",
    marca_nombre == "GT 1569" ~ "PEPE",
    marca_nombre == "GT 5297" ~ "ELVIA"
  )) %>%
  ggplot(aes(x = year, y = l_c_c, color = marca_nombre, size = l_c_c)) +
  geom_line(linewidth = 1, show.legend = FALSE) +
  geom_point(size = 4, alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = c("indianred3", "goldenrod", "palegreen4")) +
  facet_wrap(~ marca_nombre) +
  coord_fixed(ratio = 0.3) +
  labs(title = "Growth of 3 Individual Female Green Sea Turtles Over Time",
       subtitle = "in Laguna la Cruz, Kino Bay, Mexico",
       x = "Year",
       y = "Curved Carapace Length (cm)") +
  theme_bw() +
  theme(plot.title = element_text(size = 14, family = "Helvetica"),
        plot.subtitle = element_text(size = 12, family = "Helvetica"),
        strip.text.x = element_text(size = 11, family = "Helvetica", face = "bold"),
        axis.title.x = element_text(size = 11, family = "Helvetica", vjust = -1),
        axis.title.y = element_text(size = 11, family = "Helvetica", vjust = 1),
        axis.text.x = element_text(size = 9, family = "Helvetica"),
        axis.text.y = element_text(size = 10, family = "Helvetica"),
        legend.title = element_text(size = 11, family = "Helvetica"),
        legend.text = element_text(size = 10, family = "Helvetica"),
        panel.spacing = unit(1, "lines"))
  
ggsave("final_visualizations/individual_growth_over_time.jpg", device = "jpg", dpi = 500)

```

```{r time-enabled-turtle-growth, fig.width = 10, fig.height = 6}
GTBK$year = as.integer(GTBK$year)

#The issue with the animation below is that it leaves out a point in all three turtles' graphs until the end of the animation. Why? Is that because of the argument transition_reveal or is there a way I can work around it?

p <- GTBK %>%
  filter(marca_nombre %in% c(
    "GT 12261",
    "GT 1569",
    "GT 5297")) %>%
  mutate(marca_nombre = case_when(
    marca_nombre == "GT 12261" ~ "JUANA",
    marca_nombre == "GT 1569" ~ "PEPE",
    marca_nombre == "GT 5297" ~ "ELVIA"
  )) %>%
  ggplot(aes(year, l_c_c, color = marca_nombre)) +
  geom_point(size = 11, alpha = 0.7, show.legend = FALSE) +
  # geom_line(size = 1, alpha = 0.9, show.legend = FALSE) +
    scale_color_manual(values = c("indianred3", "goldenrod", "palegreen4")) +
    facet_wrap(~ marca_nombre) +
  coord_fixed(ratio = 0.3) +
  theme_bw() +
  labs(title = "Growth of 3 Individual Female Green Sea Turtles",
       subtitle = "Caught by GTBK in Laguna la Cruz, Mexico",
       x = "Year",
       y = "Curved Carapace Length (cm)") +
  transition_reveal(along = year, keep_last = FALSE) +
  # shadow_mark(color = "black", alpha = 0.3, size = 0.5, future = FALSE, past = TRUE) +
  ease_aes('linear') +
  theme(plot.title = element_text(size = 20, family = "Helvetica"),
        plot.subtitle = element_text(size = 18, family = "Helvetica"),
        strip.text.x = element_text(size = 18, family = "Helvetica", face = "bold"),
        axis.title.x = element_text(size = 18, family = "Helvetica", vjust = -1),
        axis.title.y = element_text(size = 18, family = "Helvetica", vjust = 1),
        axis.text.x = element_text(size = 16, family = "Helvetica"),
        axis.text.y = element_text(size = 16, family = "Helvetica"),
        panel.spacing = unit(1, "lines")) 

animate(p, width = 900, height = 500, nframe = 8, fps = 1, renderer = gifski_renderer(loop = TRUE))

anim_save("final_visualizations/turtlegrowth.gif", dpi = 1000)

#new attempt using transition_manual; this one will not allow me to add a geom_line because each frame is discrete and cannot be linked to other frames. This animation at least includes all three points per turtle but I wish there was some line or something at the end

GTBK %>%
  filter(marca_nombre %in% c(
    "GT 12261",
    "GT 1569",
    "GT 5297")) %>%
  mutate(marca_nombre = case_when(
    marca_nombre == "GT 12261" ~ "JUANA",
    marca_nombre == "GT 1569" ~ "PEPE",
    marca_nombre == "GT 5297" ~ "ELVIA"
  )) %>%
  ggplot(aes(year, l_c_c, color = marca_nombre)) +
  geom_point(aes(year, l_c_c, group = year), size = 4, alpha = 0.7, show.legend = FALSE) +
  geom_line(aes(group = marca_nombre), size = 1, alpha = 0.9, show.legend = FALSE) +
    scale_color_manual(values = c("indianred3", "goldenrod", "palegreen4")) +
    facet_wrap(~ marca_nombre) +
  coord_fixed(ratio = 0.3) +
  theme_bw() +
  labs(title = "Growth of 3 Individual Female Green Sea Turtles",
       subtitle = "Caught by GTBK in Laguna la Cruz, Mexico",
       x = "Year",
       y = "Curved Carapace Length (cm)") +
  transition_manual(year, cumulative = FALSE)

```

```{r sankey_2, fig.width = 8, fig.height = 8}
library(ggalluvial)

Sankey <- GTBK_data %>% 
  filter(numero_recaptura %in% c(3,4)) %>%
  mutate(yearmonth = paste(año, mes, sep = "-")) %>%
  select(marca_nombre, año) %>%
  group_by(marca_nombre, año) %>%
  summarize(n = n()) %>%
  arrange(año) #%>%
  # pivot_wider(
  #   names_from = año,
  #   values_from = n
  # ) 

# Sankey <- replace(Sankey,is.na(Sankey),0) %>%
#    mutate(frequency = n())


Sankey %>%
  group_by(marca_nombre) %>%
  # mutate(case_when(
  #   marca_nombre == "GT 1569" ~ "PEPE",
  #   marca_nombre == "GT 3843" ~ "JAN",
  #   marca_nombre == "GT 3845" ~ "LEAH",
  #   marca_nombre == "GT 11489" ~ ""
  #   marca_nombre == "GT 12"
  #   marca_nombre ==
  #   marca_nombre ==
  #   marca_nombre ==
  #   marca_nombre ==
  # )
  ggplot(
    aes(
         y = n, 
         axis1 = marca_nombre, 
         axis2 = año
         )
       ) +
  geom_alluvium(aes(fill = marca_nombre)) + 
  geom_stratum(width = 1/12, fill = "black", color = "grey") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_fill_viridis_d()

```

## Final Visualizations

```{r}

```




